services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_DATABASE: pokemondeckvault
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    ports:
      - '3306:3306'
